### ISSUE TITLE
Build got failed after 29 minutes with failure message.

### ISSUE THREAD

**Issue by Adisingh001** [ianw1974/zimbra-build-scripts#104]
**Please do not open issues relating to Zimbra itself or the operating system.  Any issues opened here should ONLY be for issues relating to the build scripts that I provide and nothing more.  You should be analysing output and error messages yourself before posting here.  Any other issues will be closed automatically.**

**Describe the bug**
The build got failed 

**To Reproduce**
1. Run this command - ./zimbra-build-helper.sh --build-zimbra
2. After running for 29 minutes it shows the error as 
'BUILD FAILED
/home/git/zimbra/zm-mailbox/build.xml:6: The following error occurred while executing this line:
/home/git/zimbra/zm-mailbox/store/build.xml:295: Problem happened while installing modules - see output for details'

**Expected behavior**
Expected to get it installed succesfully

**Screenshots**
![Screenshot from 2024-11-22 00-16-22](https://github.com/user-attachments/assets/b623e325-e7fe-4761-93e4-305a17c8a378)
![Screenshot from 2024-11-22 00-18-36](https://github.com/user-attachments/assets/1babb394-82da-4399-aef6-01ce075aa5eb)

**Desktop (please complete the following information):**
 - OS: AlmaLinux
 - Browser: Mozilla Firefox
 - Version 128.4.0-1.el8_10

**Additional context**

**Comment by ianw1974** [comment]
AlmaLinux 8 or 9?

**Comment by Adisingh001** [comment]
AlmaLinux 8

**Comment by ianw1974** [comment]
OK, I'll take a look tomorrow need to make a VM with Alma so I can find where the problem is.

**Comment by Adisingh001** [comment]
Sure, looking forward to hear with you.

**Comment by ianw1974** [comment]
I'm guessing a Java conflict with multiple JRE/JDK installed, but I'll confirm tomorrow.

**Comment by Adisingh001** [comment]
Yes, I will try it after installing the new OS.

**Comment by JimDunphy** [comment]
I have seen something similar a few years back when PATH in the build environment picked up /opt/zimbra/common/bin/ before the systems directory. 

Verify you are pulling from the OS java and not /opt/zimbra/common/bin? 

% id 
jad 

$ which java 
/usr/bin/java 

It's a long shot but a quick check instead of reloading an OS. 

Jim

**Comment by ianw1974** [comment]
Generally, a build system shouldn't be used for every day use, or even on a server where Zimbra is installed.  It is recommended that this is done separately from a live system.  It's quite easy to have a small VM purely for building purposes - I have a VM with 2vcpu, 4gb of ram and a 40GB hard disk that I use purely for building Zimbra and nothing else.  That way it's very simple to avoid these types of conflicts.

That way, you don't have to fix or get around issues when building on your Zimbra server, or on your desktop or whatever that may have conflicting packages installed.

**Comment by Adisingh001** [comment]
yes, I am using a spare server for zimbra build which will be used only for zimbra. I am trying with new OS, we'll let you know further details.

**Comment by ianw1974** [comment]
Make sure whatever OS you install, that it is a minimal installation.  If you install a graphical environment as well, you run the risk of installing multiple versions of Java and it will never work and provide you with a build.  My website has all versions for 9 and 10 built using these scripts, so the problem is your installation.

These scripts work providing you install a minimal server and then run the script to install the required dependencies.

**Comment by Adisingh001** [comment]
> Well, I just created myself an AlmaLinux 8 VM by doing a minimal installation, and then built Zimbra OK
> 
> ![Screenshot from 2024-11-21 20-40-42](https://private-user-images.githubusercontent.com/23740709/388666975-d7b1af9e-84a9-4b89-98c0-95bb2d71ef38.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyODk0NjcsIm5iZiI6MTczMjI4OTE2NywicGF0aCI6Ii8yMzc0MDcwOS8zODg2NjY5NzUtZDdiMWFmOWUtODRhOS00Yjg5LTk4YzAtOTViYjJkNzFlZjM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIyVDE1MjYwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjNWFjNjgzNGU3MDBjOTU1MjdjNDZmMmRmYmM5Y2YwNWY5MzVhMzI5MjFkNzMxMGE0YzZhZWYwOTRjNjExNzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.3cNyqBw1QXRLEfRuu4kM8tF6lx8AHxnEe4FHMgIpRN4)
> 
> As per the help parameter:
> 
> ```
> [root@alma zimbra-build-scripts]# ./zimbra-build-helper.sh --help
> 
> Zimbra Build Helper script!
> 
> Valid parameters are as follows:
> 
>   --install-deps	 - Installs required dependencies
>   --build-zimbra	 - Builds Zimbra
>   --cleanup		 - Cleanup previous attempted builds
>   --help		 - Shows this help screen
> 
> At the beginning of the script these variables can be changed if you want:
> 
> MAINDIR=/home/git
> PROJECTDIR=zimbra
> 
> Build summary step-by-step:
> 
>   1. Generate ssh key: ssh-keygen -t rsa -b 4096 -C "your_email@address"
>   2. Upload this to your GitHub profile: https://github.com/settings/keys
>   3. Only OpenJDK 8 can be installed on the build server, remove other versions
>   4. Run:./zimbra-build-helper.sh --install-deps
>   5. Copy either config.build.9 or config.build.10 to config.build
>   6. Run:./zimbra-build-helper.sh --build-zimbra
> ```
> 
> Point 3 to ensure you have only OpenJDK 8 installed on your system. I expect you are building on a machine you use regularly for other things, maybe your desktop or something since you mentioned about Firefox being installed. Since you most likely need the newer Java versions, if you cannot remove them before building Zimbra, then I suggest you do the same as me - make a clean VM minimal installation and use this VM only for building Zimbra.
> 
> ```
> [root@alma zimbra-build-scripts]# rpm -qa | grep -i jdk
> copy-jdk-configs-4.0-2.el8.noarch
> java-1.8.0-openjdk-1.8.0.432.b06-2.el8.x86_64
> java-1.8.0-openjdk-devel-1.8.0.432.b06-2.el8.x86_64
> java-1.8.0-openjdk-headless-1.8.0.432.b06-2.el8.x86_64
> ```
> 
> that is how the system should look. Therefore the scripts work fine, the problem is your machine has conflicting packages installed.

For me the same thing is showing which you have sent in the ss, next what I need to do can you please guide me with the steps.
