### ISSUE TITLE
WIP - Docker/Podman Support

### ISSUE THREAD

**Issue by ianw1974** [ianw1974/zimbra-build-scripts#13]
Currently a work in progress which will be documented here.

The current ```Dockerfile``` was created for Ubuntu 18.04 from this pull request: https://github.com/ianw1974/zimbra-build-scripts/pull/12

The plan is to adapt this in a similar way that the main Zimbra Build Helper script works, to simplify the docker/podman commands for building Zimbra for various distributions.

**Comment by ianw1974** [comment]
The `Dockerfile` currently supports building for the following Linux distributions:

- Almalinux 8.6
- Oracle Linux 8.6
- Rocky Linux 8.6
- Ubuntu 18.04

no docker build support will be offered for CentOS (EOL and not recommended for use), RHEL (due to using microdnf), Ubuntu 16.04 (EOL).

**Comment by ianw1974** [comment]
Builds have been made for Alma, Oracle, Rocky and Ubuntu.  Whilst not installed to see if Zimbra works, there *shouldn't* be any problems with the builds.

**Comment by ianw1974** [comment]
As Zimbra have now fixed their repositories for Ubuntu 20.04 for the packages that couldn't be installed (issue #10), the scripts have now been amended to re-add building for Ubuntu 20.04.

Currently testing build process for Ubuntu 20.04 under docker/podman.

**Comment by ianw1974** [comment]
Docker builds Ubuntu 20.04 without issues.  Minor change to Dockerfile relating to tzdata package and configuring automatically, else problem occurs.

@maxxer just in case you need Ubuntu 20.04 support, it now works :)

**Comment by maxxer** [comment]
Out of curiosity, did you replace `podman` with `docker` for a specific reason or for convenience?

**Comment by ianw1974** [comment]
Purely that docker is probably the most used at present - that's the only reason.  Podman tends to be more geared towards RHEL distros (developed by Red Hat).  Should that change in the future, then will re-reference docker with podman.

**Comment by ianw1974** [comment]
Looking at RHEL UBI images for building under docker/podman doesn't look like it will be possible.  Whilst the CodeReady Builder repositories are there, as well as Base and AppStream, any additional ones cannot be obtained without having a Red Hat Subscription.  This means without this, we cannot install the Development Tools Group, or enable the appropriate modules for installing ```ant``` and ```ant-junit``` which come in  ```javapackages-tools``` package.

**Comment by ianw1974** [comment]
Closing this as pretty much everything works as intended.  RHEL can always be built normally anyway on a VM.
