### ISSUE TITLE
Request: builder script for third party packages

### ISSUE THREAD

**Issue by biji** [ianw1974/zimbra-build-scripts#14]
Would you please create helper script for building third party packages:

https://github.com/Zimbra/packages

**Comment by ianw1974** [comment]
Hi,

Sorry I don't have time to manage/maintain such a huge task.  There are well over 185-190 packages to build, zero mention of what dependencies are required to be installed for each of those 185-190 packages.

My build scripts build Zimbra and the included third-party components anyway for a particular Zimbra release or patch release.  So I don't see any need or reason to do this as well.  Running my build scripts every 3 - 6 months builds a new Zimbra version which should include new components that Zimbra include in their zm-build repository for that particular version/release.
