### ISSUE TITLE
build failure on ubuntu 16.04

### ISSUE THREAD

**Issue by ErickPH** [ianw1974/zimbra-build-scripts#15]
[putty.log](https://github.com/ianw1974/zimbra-build-scripts/files/11655914/putty.log)
I have attached puty.log which details the build failure.
/home/git/zimbra/zm-mailbox/build-common.xml:576: Directory does not exist: /root/.ivy2/cache

I see references to ivy but not to ivy2.

Please advise.

**Comment by ErickPH** [comment]
[putty.log](https://github.com/ianw1974/zimbra-build-scripts/files/11655919/putty.log)

putty log

**Comment by ErickPH** [comment]
FWIW ant and ivy for the versions you get after you do an apt-update, will create an .ivy directory instead of the new .ivy2 
To assist the build to finish successfully, this can be set by various methods such as ANT_OPTS=-Divy.default.ivy.user.dir=${user.home}/.ivy2

And yes, Ubuntu 16 is very old. I was just following the build page from Zimbra and they list 16.0.4 as the first example so I played along (and failed) 

Many thanks for pointing this out, I will make a build on Alma 8.8 and see where that goes.

**Comment by ianw1974** [comment]
Alma will build. I have them all up on my site built on 2023.06.01 so few days ago.
