### ISSUE TITLE
not an issue but special build request

### ISSUE THREAD

**Issue by ErickPH** [ianw1974/zimbra-build-scripts#17]
Can I buy you N number of coffees for a special build that includes this patch:
https://github.com/Zimbra/zm-web-client/pull/822/files
It allows disabling the offering of the modern UI on FOSS builds.
Not being an experienced dev I don't know how to track if this is already on the latest Z10 build that will be pulled with the scripts.

**Comment by ianw1974** [comment]
Hi,

Let me check into it to see what the status is.  If not, I should be able to add this to the build process to patch it.

**Comment by ianw1974** [comment]
Hi,

Commit is generally available.  I'm building for all distros as I write and they'll be available later on: https://techfiles.online/zimbra/

The site will show a build date of "2023-06-30" once uploaded and ready for download.

**Comment by ianw1974** [comment]
Builds just gone online.  They should have the mobile url fix in it, to allow for it to be enabled/disabled.
