### ISSUE TITLE
All build installs failing on mailboxd when generating SSL certs

### ISSUE THREAD

**Issue by ianw1974** [ianw1974/zimbra-build-scripts#28]
All builds that previously were working now failing with the following error during installation:

```
ERROR: openssl pkcs12 export to '/opt/zimbra/ssl/zimbra/jetty.pkcs12' failed(1):
Error creating PKCS12 MAC; no PKCS12KDF support?
Use -nomac if MAC not required and PKCS12KDF support not available.
80B52438437F0000:error:0308010C:digital envelope routines:inner_evp_generic_fetch:unsupported:crypto/evp/evp_fetch.c:373:Global default library context, Algorithm (PKCS12KDF : 192), Properties (<null>)
80B52438437F0000:error:1180006B:PKCS12 routines:pkcs12_gen_mac:key gen error:crypto/pkcs12/p12_mutl.c:147:
80B52438437F0000:error:1180006D:PKCS12 routines:PKCS12_set_mac:mac generation error:crypto/pkcs12/p12_mutl.c:220:
Thu Aug 10 18:42:42 2023 failed.
```

All of my builds have been removed from my site until I can make fresh builds to find out where the problem has been introduced (since this could break existing installs when upgrading).  They used to work previously which means something changed between July and August 2023.

All updates related to this problem will be provided in this issue.

**Comment by ianw1974** [comment]
From testing an initial RHEL build, it seems that it has now passed the point of failure during installation:

```
Initializing core config...Setting up CA...done.
Deploying CA to /opt/zimbra/conf/ca ...done.
Creating SSL zimbra-store certificate...done.
Creating new zimbra-ldap SSL certificate...done.
Creating new zimbra-mta SSL certificate...done.
Creating new zimbra-proxy SSL certificate...done.
Installing mailboxd SSL certificates...done.
Installing MTA SSL certificates...done.
Installing LDAP SSL certificate...done.
Installing Proxy SSL certificate...done.
```

this was previously failing at:

```
Installing mailboxd SSL certificates...failed.
```

currently verifying a ZCS-9 build, will be verifying ZCS-10 after this.

**Comment by ianw1974** [comment]
Zimbra 10 build working also for RHEL.

Remaining builds need to be made and uploaded to my site shorly.

**Comment by ibrahimtopbasi** [comment]
change cert on nginx. this solves your problem
