### ISSUE TITLE
Change build version to reflect patch level present on them

### ISSUE THREAD

**Issue by lovelord83** [ianw1974/zimbra-build-scripts#48]
Hi there ianw1974, 

I was thinking about patch level not present in your builds available on website and this could be confusing for someone reaching website for first time.

Let me explain with a sample:

**UBUNTU 18.04**
zcs-10.0.**0**_GA_0001.UBUNTU18_64.20231003091546.tgz

**UBUNTU 20.04**
zcs-10.0.**0**_GA_0001.UBUNTU20_64.20231003093215.tgz

if those build are based on Daffodil patch 5 them should be

**UBUNTU 18.04**
zcs-10.0.**5**_GA_0001.UBUNTU18_64.20231003091546.tgz
 
**UBUNTU 20.04**
zcs-10.0.**5**_GA_0001.UBUNTU20_64.20231003093215.tgz

otherwise could be unclear to someone (TBH even to me). 

Am I wrong or missleading something?

Cheers

**Comment by ianw1974** [comment]
Hi,

Yes correct it could be misleading.  Even Zimbra builds downloadable from zimbra.com/downloads are built from March with 10.0.0.  I have updated config.build.10 on the repository, so future builds I run will show 10.0.5 as the version.  If I get chance I'll redo them shortly to fix the potential confusion.

Despite this though, the builds are the latest so whilst the filename shows 10.0.0 it will actually be 10.0.5.

**Comment by lovelord83** [comment]
Yeah, you got the point. That is a little bit confusing because if you land for first time on website and look on filename you could think that are not last builds available, instead the available builds are the most recent actually. It could be a good idea to pre-fetch build version and automatically modify config.build.XX to set "BUILD_NO" , than building. Doing like that , automatically produce builds with correct filename, no matter what.

**Comment by ianw1974** [comment]
I'm probably going to deal with the BUILD_NO in a different way.  Since I build generally every quarter, I will effectively use the first two digits to refer to the quarter, 01, 02, 03, 04 and the last two digits for year, so 23 in this case.  That will generally clear that up.  I may even change the BUILD_RELEASE_CANDIDATE to ```GA-techfiles``` to at least give an idea where it came from.  But I will have to check/test that to see if it will build with this, as unsure if Zimbra have a requirement that it's GA, ALPHA, BETA or something along those lines.

**Comment by lovelord83** [comment]
Yeah, I think that should be more than enough to perfectly understand which version you're actually downloading. Otherwise there's no clue to understand actually if you're downloading a Q2 or Q3 file from archive. Well done!

**Comment by lovelord83** [comment]
> Yeah, I think that should be more than enough to perfectly understand which version you're actually downloading. Otherwise there's no clue to understand actually if you're downloading a Q2 or Q3 file from archive. Well done!

Not totally true BTW, because you got timestamp in filename tail : 

Ex. [...].20231003093215.tgz

in any case, is better to be more than less clear :)

**Comment by ianw1974** [comment]
> Ex. [...].20231003093215.tgz

Ha yeah I forgot about that, but the four digits will be even clearer than looking through the long digit trying to work out the build date.

**Comment by ianw1974** [comment]
Well GA cannot be changed, but I have started making builds which change the build number automatically, first two digits referring to the quarter, and the second two digits referring to the year.

They should be up on the site pretty much towards the end of the day.

**Comment by lovelord83** [comment]
> Well GA cannot be changed

Ok, so BUILD_RELEASE_CANDIDATE cannot be modified, good to know. 
Anyway, I suppose that we're only interested in BUILD_NO + BUILD_RELEASE_NO moving from 0001 to 0423 (actually) and from 10.0.0 to 10.0.5 (actually). System will pre-format build template like this, if I've understand what you've done

Example: 

```
BUILD_NO                = 0423
BUILD_RELEASE           = DAFFODIL
BUILD_RELEASE_NO        = 10.0.0
BUILD_RELEASE_CANDIDATE = GA
BUILD_TYPE              = FOSS
BUILD_THIRDPARTY_SERVER = files.zimbra.com
INTERACTIVE             = 0
```

Producing a file name similar to: zcs-10.0.5_GA_0423.UBUNTU20_64.20231031163615.tgz

This seems pretty good and way more intelligible. Well done!

**Comment by ianw1974** [comment]
See below how the naming convention works out:

```
├── alma
│   ├── zcs-10.0.5_GA_0423.RHEL8_64.20231031130547.tgz
│   ├── zcs-10.0.5_GA_0423.RHEL8_64.20231031130547.tgz.md5
│   ├── zcs-9.0.0_GA_0423.RHEL8_64.20231031113025.tgz
│   └── zcs-9.0.0_GA_0423.RHEL8_64.20231031113025.tgz.md5
├── oracle
│   ├── zcs-10.0.5_GA_0423.RHEL8_64.20231031132005.tgz
│   ├── zcs-10.0.5_GA_0423.RHEL8_64.20231031132005.tgz.md5
│   ├── zcs-9.0.0_GA_0423.RHEL8_64.20231031114519.tgz
│   └── zcs-9.0.0_GA_0423.RHEL8_64.20231031114519.tgz.md5
├── rocky
│   ├── zcs-10.0.5_GA_0423.RHEL8_64.20231031133457.tgz
│   ├── zcs-10.0.5_GA_0423.RHEL8_64.20231031133457.tgz.md5
│   ├── zcs-9.0.0_GA_0423.RHEL8_64.20231031120011.tgz
│   └── zcs-9.0.0_GA_0423.RHEL8_64.20231031120011.tgz.md5
└── ubuntu
    ├── zcs-10.0.5_GA_0423.UBUNTU18_64.20231031134821.tgz
    ├── zcs-10.0.5_GA_0423.UBUNTU18_64.20231031134821.tgz.md5
    ├── zcs-10.0.5_GA_0423.UBUNTU20_64.20231031140352.tgz
    ├── zcs-10.0.5_GA_0423.UBUNTU20_64.20231031140352.tgz.md5
    ├── zcs-9.0.0_GA_0423.UBUNTU18_64.20231031121420.tgz
    ├── zcs-9.0.0_GA_0423.UBUNTU18_64.20231031121420.tgz.md5
    ├── zcs-9.0.0_GA_0423.UBUNTU20_64.20231031123022.tgz
    └── zcs-9.0.0_GA_0423.UBUNTU20_64.20231031123022.tgz.md5
```

these are the builds created today which will be uploaded to the site shortly.

**Comment by lovelord83** [comment]
Very nice work Ian!

**Comment by ianw1974** [comment]
For completeness, in the discussion section here some clarification as to how everything is being addressed: https://github.com/ianw1974/zimbra-build-scripts/discussions/50

I think that's probably the best way forward, especially also in relation to prior discussions relating to the patch number and figured in the discussion it might be more visible than trying to find it through previously opened issues, etc.

Builds are up and ready, feel free to check them out :)
