### ISSUE TITLE
Request to support AlmaLinux 8

### ISSUE THREAD

**Issue by donatid** [ianw1974/zimbra-build-scripts#6]
Hi Ian,

Thank you for your effort to create an automation script to build Zimbra binary packages.
Please add AlmaLinux 8 to your scripts.

Thanks

**Comment by ianw1974** [comment]
Hi @donatid thanks for opening the issue.  Give me a short while to build this, I've pulled the patch from zmbuild project so will be easy to integrate with my scripts.

Once the build process has been tested, I'll then make the appropriate commits here and close the issue as resolved at that moment.  Shouldn't take me too long to get a test system ready with Alma Linux.

**Comment by donatid** [comment]
Wow, it's fast!
Thank you.

**Comment by ianw1974** [comment]
My pleasure.  For those who don't want to build themselves, the build for AlmaLinux will be up on my site shortly.
