### ISSUE TITLE
HTTP 404 after connecting to the interface to view emails

### ISSUE THREAD

**Issue by thanaus** [ianw1974/zimbra-build-scripts#65]
Hello,

First of all, thank you for all the work you have done !

I installed on a server the Zimbra Ubuntu 20.04 release that I downloaded from your site and I have an issue after connecting to the interface to view emails.

The URL on my browser is https://xxxx.yyyy.com/modern

![image](https://github.com/ianw1974/zimbra-build-scripts/assets/52779711/9f9858bc-e41e-4a75-b6ba-670d5e38090c)

In the inspector of my browser, there is a 404 error for this URL.
Any idea ?

Best regards,

**Comment by ianw1974** [comment]
Hi,

This is a question you should be asking on the Zimbra forums - https://forums.zimbra.org - Zimbra configured it to use modern interface by default, so it means you need to edit the COS to not use the Modern web interface.  This has been covered already on the Zimbra forums.

Support here is for the build process **only**.

**Comment by ianw1974** [comment]
Most likely something in Zimbra's code defaults it to this.

**Comment by ianw1974** [comment]
The reason why innotel, is because they do this in their instructions:

```
#Disable Modern UI

nano /opt/zimbra/jetty_base/webapps/zimbra/WEB-INF/classes/messages/ZmMsg.properties

#Edit lines (673, 679, 680)to reflect

clientAdvanced = Default
clientPreferred =
clientModern =
```

the preferred way is as mentioned in my previous post by logging into Zimbra WebAdmin and edit default COS - which most likely does a similar thing, eg: update the text file, or perhaps other stuff in the background.

**Comment by derritter88** [comment]
Just as an additional info: 
Most values within Zimbra admin cannot be configured as I get several SOAP errors.

What worked was following CLI command with zimbra user:
`zmprov mcf zimbraModernWebClientDisabled TRUE` & `zmmailboxdctl restart` afterwards.
