### ISSUE TITLE
Official support ubuntu 22.04 LTS?

### ISSUE THREAD

**Issue by alsyundawy** [ianw1974/zimbra-build-scripts#68]
Official support ubuntu 22.04 LTS?

**Comment by ianw1974** [comment]
Zimbra/Synacor don't even support it yet.  Official Zimbra downloads don't have it: https://www.zimbra.com/product/download/zimbra-collaboration-network-edition/

I cannot support it until they do.  You should be asking them.  I believe sometime in 2024 they will do it (according to the forums).
