### ISSUE TITLE
rockylinux 8.6 failed when build

### ISSUE THREAD

**Issue by alsyundawy** [ianw1974/zimbra-build-scripts#8]
BUILD_NO = 2005
BUILD_RELEASE = KEPLER
BUILD_RELEASE_NO = 9.0.0
BUILD_RELEASE_CANDIDATE = GA
BUILD_TYPE = FOSS
BUILD_THIRDPARTY_SERVER = files.zimbra.com
INTERACTIVE = 0

#############
# Variables #
#############
MAINDIR=/home/git
PROJECTDIR=zimbra
ZM_BRANCH_TAG=9.0.0.p25

===========================================================================================
FAILURE MSG : Could not determine BUILD_ARCH

===========================================================================================
--Stack Trace-- (62390)
./build.pl:146 called from main::GetBuildArch
./build.pl:83 called from main::__ANON__
./build.pl:176 called from main::LoadConfiguration
./build.pl:1070 called from main::InitGlobalBuildVars
./build.pl:1086 called from main::main

===========================================================================================
END at ./build.pl line 1062.

There was a problem with the build process, check output above!

<img width="451" alt="image" src="https://user-images.githubusercontent.com/6451849/169713470-e97c948a-0107-44cf-bb16-23cecc0d68f9.png">

**Comment by ianw1974** [comment]
Hi,

Thx for reporting.  As it happens Zimbra removed Rocky support from the get_plag_tag.sh file, so I had to re-add the patch.  The commit has now been made to the repo fixing this, so you can pull/reclone and it will work for you.

Since you've edited zimbra-build-helper.sh, the easiest will be:

```
git checkout -- .
git pull
```

and then remake your changes to the script to use ```9.0.0.p25``` instead of ```develop``` branch.

**Comment by ianw1974** [comment]
You will have more success building from the develop branch.  Checking out an older tag is more problematic.  The develop branch builds the latest Zimbra version, it doesn't necessarily mean that it will be unstable.  I have just built Zimbra for Rocky 8.6 using develop branch.  Tag 9.0.0.p25 doesn't work.

**Comment by alsyundawy** [comment]
ok thx i will report if get error when build on other distro like alma & centos

**Comment by ianw1974** [comment]
As you can see in the errors, that is due to Zimbra's repositories, so I cannot do anything about that.  Obviously Zimbra broke building for CentOS 7

**Comment by alsyundawy** [comment]
ok, will trying again. thx for your help, terima kasih
