### ISSUE TITLE
zimbra 10.1 & ubuntu 22.04

### ISSUE THREAD

**Issue by alsyundawy** [ianw1974/zimbra-build-scripts#89]
can you support 

zimbra 10.1 & ubuntu 22.04

**Comment by ianw1974** [comment]
I will take a look at integrating it shortly yes.

**Comment by alsyundawy** [comment]
thx

**Comment by ianw1974** [comment]
We can leave the issue open, I'll update once I've integrated support and at that point we can close it :)

**Comment by ianw1974** [comment]
I'm checking the build process now to see if I can get a ```10.1.0``` Zimbra build made.  If all goes well it should be up on my site later, as well as appropriate commits being made to this repo where required.

**Comment by ianw1974** [comment]
See discussion for more details, but support for Ubuntu 22.04 and version 10.1.0 should be OK: https://github.com/ianw1974/zimbra-build-scripts/discussions/94
