### ISSUE TITLE
error build on centos 7

### ISSUE THREAD

**Issue by alsyundawy** [ianw1974/zimbra-build-scripts#9]
=========================================================================================================
FAILURE MSG : cmd='git clone --depth=1 -b develop https://github.com/Zimbra/ant-1.7.0-ziputil-patched.git /home/git/zimbra/ant-1.7.0-ziputil-patched'
EXTRA INFO  : 'git clone --depth=1 -b develop https://github.com/Zimbra/ant-1.7.0-ziputil-patched.git /home/git/zimbra/ant-1.7.0-ziputil-patched' exited with value 128

=========================================================================================================
--Stack Trace-- (1817)
./build.pl:824 called from main::SysExec
./build.pl:399 called from main::Clone
./build.pl:1076 called from main::Checkout
./build.pl:1086 called from main::main

=========================================================================================================
END at ./build.pl line 1062.

There was a problem with the build process, check output above!

<img width="563" alt="image" src="https://user-images.githubusercontent.com/6451849/169769385-f08ba7df-b68c-4f60-98b4-f4ef94d5b620.png">

#############
# Variables #
#############
MAINDIR=/home/git
PROJECTDIR=zimbra
ZM_BRANCH_TAG=9.0.0.p25

BUILD_NO = 2022
BUILD_RELEASE = KEPLER
BUILD_RELEASE_NO = 9.0.0
BUILD_RELEASE_CANDIDATE = GA
BUILD_TYPE = FOSS
BUILD_THIRDPARTY_SERVER = files.zimbra.com
INTERACTIVE = 0

Linux Machine 6 Core 12 Treads x 2 CPU WIth 12 GB Memory RAM

**Comment by ianw1974** [comment]
I have removed support for building from tags because it is broken from Zimbra's side.  Also, what you reported is problems with Zimbra's repositories - it has nothing to do with my scripts.  Obviously they have broken their build process.

**Comment by alsyundawy** [comment]
but if change to develop its running build. its must using ZM_BRANCH_TAG=develop always?

**Comment by ianw1974** [comment]
Yes, now scripts will only use develop because using tags is broken from Zimbra's side.  So my scripts are now hard-coded to use develop.  I am not going to give ability to build from tags when it doesn't work from Zimbra's side.  It's pointless.  People the open issues saying it doesn't work and it has nothing to do with my scripts.  If Zimbra break the ability to build from their tags, then there is nothing I can do about it.

As it works from develop, then that is the best way to build and not try to build from tags.

**Comment by ianw1974** [comment]
I quote your error:

```
FAILURE MSG : cmd='git clone --depth=1 -b develop https://github.com/Zimbra/ant-1.7.0-ziputil-patched.git /home/git/zimbra/ant-1.7.0-ziputil-patched'
EXTRA INFO : 'git clone --depth=1 -b develop https://github.com/Zimbra/ant-1.7.0-ziputil-patched.git /home/git/zimbra/ant-1.7.0-ziputil-patched' exited with value 128
```

That is Zimbra's repositories, the error is there, which means building from tags doesn't work, so it's obvious.  develop is the only way to build successfully.  If you want to build from tags, it would mean opening the issue on zm-build zimbra repository.

**Comment by alsyundawy** [comment]
thx for your support, will try again. terima kasih

**Comment by alsyundawy** [comment]
OK thx again, building zimbra9 now on el7 success without problem

Terima Kasih Banyak

**Comment by ianw1974** [comment]
Glad to hear, mine also worked on rhel7 and rhel8.  Rocky and Alma too.  So CentOS should also be OK.
